language: julia
julia:
  - 1.1

after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg; cd(Pkg.dir("Jtac")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
